# base image
FROM python:3.11

# set working directory
WORKDIR /app

# copy requirements file
COPY . /app

# install dependencies
RUN pip install -r requirements.txt

# expose port
EXPOSE 8000
# command to run the application
CMD ["python", "./main.py"]